image: docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

services:
- docker:dind

build:
  script:
  - docker build -t build .
  - docker run --rm -v "$(pwd)":/out build cp -R /opt/eaas-proxy/. /out/eaas-proxy
  artifacts:
    paths:
    - eaas-proxy/

pages:
  stage: deploy
  image: node
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - npm install
  - npm run build
  - rm -rf .git
  - mkdir public
  - mv .* * public/. || true
  artifacts:
    paths:
    - public
  only:
  - master
