image: docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

services:
- docker:dind

build:
  script:
  - docker build -t build .
  - docker run --rm -v "$(pwd)":/out build cp -R /opt/eaas-proxy/. /out/eaas-proxy
  artifacts:
    paths:
    - eaas-proxy/

pages:
  stage: deploy
  image: node
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - npm install
  - npm run build || true
  - apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y default-jre
  - (cd emulator/v86; git apply ../v86-esm.patch; make)
  - rm -rf .git
  - find -maxdepth 1 -lname . -delete # HACK: Fix: pages:deploy - Symlink cannot be created targeting: .
  - mkdir public
  - mv .* * public/. || true
  artifacts:
    paths:
    - public
  only:
  - master
